version: '2.2'
services:
  discovery:
    image: consul:0.9.3
    hostname: discovery
    environment:
      - 'CONSUL_LOCAL_CONFIG={"datacenter": "demo_dc"}'
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    networks:
      - demo

  messaging:
    image: pivotalrabbitmq/rabbitmq-autocluster:3.6.12
    environment:
      - TCP_PORTS=15672, 5672
      - AUTOCLUSTER_TYPE=consul
      - AUTOCLUSTER_DELAY=60
      - CONSUL_HOST=discovery
      - CONSUL_SVC_ADDR_AUTO=true
      - AUTOCLUSTER_CLEANUP=true
      - CLEANUP_WARN_ONLY=false
      - CONSUL_DEREGISTER_AFTER=60
    ports:
      - "15672:15672"
    expose:
      - 5672
      - 5671
      - 15671
    networks:
      - demo
    depends_on:
      discovery:
        condition: service_started

  cache:
    image: datawave/hazelcast-server
    scale: 3
    command:
      - --spring.output.ansi.enabled=ALWAYS
      - --spring.cloud.consul.host=discovery
    networks:
      - demo

  configuration:
    image: datawave/config-service
    command:
      - --spring.output.ansi.enabled=ALWAYS
      - --spring.profiles.active=dev,consul,native
      - --spring.cloud.consul.host=discovery
      - --spring.cloud.bus.enabled=true
      - --management.health.rabbit.enabled=true
      - --spring.cloud.config.server.native.searchLocations=file:///microservice-config
    ports:
      - "8888:8888"
    volumes:
      - ${CONFIG_DIR:-./config}:/microservice-config:ro
    networks:
      - demo
    depends_on:
      messaging:
        condition: service_started

  audit:
    image: datawave/audit-service
    command:
      - --spring.output.ansi.enabled=ALWAYS
      - --spring.profiles.active=consul
      - --spring.cloud.consul.host=discovery
    ports:
      - "8080:8080"
    networks:
      - demo
    healthcheck:
      test: curl -f http://localhost:8080/datawave/mgmt/health
    depends_on:
      messaging:
        condition: service_started

networks:
  demo:
