---
# Sets up DATAWAVE builds on a gitlab runner

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository

build_and_test:
  stage: test
  image: maven:3.5.3-jdk-8
  before_script:
    - useradd -d ${CI_PROJECT_DIR} -g users -M -N datawave
    - chown -R datawave:users ..
  script:
    - |
      su -l -p datawave << EOS
      mvn $MAVEN_CLI_OPTS clean install -Ddist -Dservices -Pdev,examples,assemble -T1C
      EOS
  retry: 2

deploy_and_test:
  stage: deploy
  variables:
    DW_DATAWAVE_BUILD_COMMAND: "mvn ${MAVEN_CLI_OPTS} -Pdev -Ddeploy -Dtar -Dservices -DskipTests clean install"
    IMAGE_REGISTRY: "674433211256.dkr.ecr.us-east-1.amazonaws.com"
    IMAGE_NAME: "datawave/quickstart"
    REMOTE_IMAGE_NAME: "${IMAGE_REGISTRY}/${IMAGE_NAME}"
    DOCKER_BUILD_OPTS: "--squash --force-rm"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
     - contrib/datawave-quickstart/bin/services/*/*.tar.gz
     - .m2/repository
  script:
    - |
      export DW_DATAWAVE_BUILD_COMMAND
      TAG="$(mvn -q -N -Dexec.executable='echo' -Dexec.args='${project.version}' exec:exec)"
      contrib/datawave-quickstart/docker/docker-build.sh ${TAG} --docker-opts "${DOCKER_BUILD_OPTS}"
      docker tag ${IMAGE_NAME}:${TAG} ${REMOTE_IMAGE_NAME}:${TAG}
      docker push ${REMOTE_IMAGE_NAME}:${TAG}
  tags:
    - datawave
    - shell-executor
