

properties:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

  - name:
    description:

