apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accumulo.fullname" . }}-gc
  labels:
    {{- include "accumulo.labels" . | nindent 4 }}
    app.kubernetes.io/component: gc
spec:
  replicas: {{ .Values.gc.replicaCount }}
  selector:
    matchLabels:
      {{- include "accumulo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gc
  template:
    metadata:
      labels:
        {{- include "accumulo.labels" . | nindent 8 }}
        app.kubernetes.io/component: gc
    spec:
      containers:
      - name: accumulo-gc
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - gc
        env:
        - name: ACCUMULO_CONF_DIR
          value: {{ .Values.config.path }}
        resources:
          {{- toYaml .Values.gc.resources | nindent 10 }}
      {{- with .Values.gc.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gc.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gc.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
